module.exports = {
	RECEIVE_ITEMS: 'RECEIVE_ITEMS',
	RECEIVE_ITEM: 'RECEIVE_ITEM',
	NEW_ITEM: 'NEW_ITEM',
	CANCEL_ITEM: 'CANCEL_ITEM',
	EXTEND_ITEM: 'EXTEND_ITEM',
	SAVE_ITEM: 'SAVE_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	EDIT_ITEM: 'EDIT_ITEM',
	UPDATE_ITEM: 'UPDATE_ITEM'
};